# Generated by Django 3.1.7 on 2021-04-05 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookpaths_app', '0004_bookpathstep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpath',
            name='author',
        ),
        migrations.AddField(
            model_name='bookpath',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='proposed_paths', to='bookpaths_app.user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='bookpath',
            name='category',
        ),
        migrations.AddField(
            model_name='bookpath',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='bookpaths_app.category'),
            preserve_default=False,
        ),
    ]
