# Generated by Django 3.1.7 on 2021-04-06 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookpaths_app', '0005_auto_20210405_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpathstep',
            name='bookpath',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookpath_steps', to='bookpaths_app.bookpath'),
        ),
        migrations.AlterUniqueTogether(
            name='bookpathfollow',
            unique_together={('bookpath', 'follower')},
        ),
    ]
