# Generated by Django 3.1.7 on 2021-04-21 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookpaths_app', '0006_auto_20210406_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpathfollow',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not started'), (1, 'Work in progress'), (2, 'Bookpath completed')], default=0),
        ),
        migrations.AlterField(
            model_name='bookpathstep',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_step', to='bookpaths_app.book'),
        ),
    ]
